package com.automobile.model;

// Generated 2015-4-7 21:58:34 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TAutoType generated by hbm2java
 */
@Entity
@Table(name = "t_auto_type", catalog = "automobile_db", uniqueConstraints = @UniqueConstraint(columnNames = "auto_type_id"))
public class AutoType implements java.io.Serializable {

	private Integer id;
	private String autoTypeId;
	private String autoType;
	private String autoTypeName;
	private String autoLevel;
	private Double autoWidth;
	private Double autoLength;
	private Double autoHeight;
	private Double axleBase;
	private Double frontGauge;
	private Double rearGauge;
	private String chassisCons;
	private Integer chassisGauge;
	private Double emissions;
	private String engineConfig;
	private String driveMode;
	private String suspensionSystem;
	private String powerType;
	private String linearType;
	private String tyreSize;
	private Double netWeight;
	private Double maxTotalMass;
	private Integer doorNum;
	private Integer searting;
	private Double bootVol;
	private Double fuelTank;
	private Integer autoColor;
	private String antennaType;
	private String autoWindow;
	private Date createtime;
	private Date updatetime;
	private String functionConfig;
	private String comfortConfig;
	private String safeConfig;
	private String remark;

	public AutoType() {
	}

	public AutoType(String autoTypeId, String autoType, String autoLevel,
			String powerType) {
		this.autoTypeId = autoTypeId;
		this.autoType = autoType;
		this.autoLevel = autoLevel;
		this.powerType = powerType;
	}

	public AutoType(String autoTypeId, String autoType, String autoTypeName,
			String autoLevel, Double autoWidth, Double autoLength,
			Double autoHeight, Double axleBase, Double frontGauge,
			Double rearGauge, String chassisCons, Integer chassisGauge,
			Double emissions, String engineConfig, String driveMode,
			String suspensionSystem, String powerType, String linearType,
			String tyreSize, Double netWeight, Double maxTotalMass,
			Integer doorNum, Integer searting, Double bootVol, Double fuelTank,
			Integer autoColor, String antennaType, String autoWindow,
			Date createtime, Date updatetime, String functionConfig,
			String comfortConfig, String safeConfig, String remark) {
		this.autoTypeId = autoTypeId;
		this.autoType = autoType;
		this.autoTypeName = autoTypeName;
		this.autoLevel = autoLevel;
		this.autoWidth = autoWidth;
		this.autoLength = autoLength;
		this.autoHeight = autoHeight;
		this.axleBase = axleBase;
		this.frontGauge = frontGauge;
		this.rearGauge = rearGauge;
		this.chassisCons = chassisCons;
		this.chassisGauge = chassisGauge;
		this.emissions = emissions;
		this.engineConfig = engineConfig;
		this.driveMode = driveMode;
		this.suspensionSystem = suspensionSystem;
		this.powerType = powerType;
		this.linearType = linearType;
		this.tyreSize = tyreSize;
		this.netWeight = netWeight;
		this.maxTotalMass = maxTotalMass;
		this.doorNum = doorNum;
		this.searting = searting;
		this.bootVol = bootVol;
		this.fuelTank = fuelTank;
		this.autoColor = autoColor;
		this.antennaType = antennaType;
		this.autoWindow = autoWindow;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.functionConfig = functionConfig;
		this.comfortConfig = comfortConfig;
		this.safeConfig = safeConfig;
		this.remark = remark;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "auto_type_id", unique = true, nullable = false, length = 20)
	public String getAutoTypeId() {
		return this.autoTypeId;
	}

	public void setAutoTypeId(String autoTypeId) {
		this.autoTypeId = autoTypeId;
	}

	@Column(name = "auto_type", nullable = false, length = 20)
	public String getAutoType() {
		return this.autoType;
	}

	public void setAutoType(String autoType) {
		this.autoType = autoType;
	}

	@Column(name = "auto_type_name", length = 20)
	public String getAutoTypeName() {
		return this.autoTypeName;
	}

	public void setAutoTypeName(String autoTypeName) {
		this.autoTypeName = autoTypeName;
	}

	@Column(name = "auto_level", nullable = false, length = 20)
	public String getAutoLevel() {
		return this.autoLevel;
	}

	public void setAutoLevel(String autoLevel) {
		this.autoLevel = autoLevel;
	}

	@Column(name = "auto_width", precision = 22, scale = 0)
	public Double getAutoWidth() {
		return this.autoWidth;
	}

	public void setAutoWidth(Double autoWidth) {
		this.autoWidth = autoWidth;
	}

	@Column(name = "auto_length", precision = 22, scale = 0)
	public Double getAutoLength() {
		return this.autoLength;
	}

	public void setAutoLength(Double autoLength) {
		this.autoLength = autoLength;
	}

	@Column(name = "auto_height", precision = 22, scale = 0)
	public Double getAutoHeight() {
		return this.autoHeight;
	}

	public void setAutoHeight(Double autoHeight) {
		this.autoHeight = autoHeight;
	}

	@Column(name = "axle_base", precision = 22, scale = 0)
	public Double getAxleBase() {
		return this.axleBase;
	}

	public void setAxleBase(Double axleBase) {
		this.axleBase = axleBase;
	}

	@Column(name = "front_gauge", precision = 22, scale = 0)
	public Double getFrontGauge() {
		return this.frontGauge;
	}

	public void setFrontGauge(Double frontGauge) {
		this.frontGauge = frontGauge;
	}

	@Column(name = "rear_gauge", precision = 22, scale = 0)
	public Double getRearGauge() {
		return this.rearGauge;
	}

	public void setRearGauge(Double rearGauge) {
		this.rearGauge = rearGauge;
	}

	@Column(name = "chassis_cons", length = 5)
	public String getChassisCons() {
		return this.chassisCons;
	}

	public void setChassisCons(String chassisCons) {
		this.chassisCons = chassisCons;
	}

	@Column(name = "chassis_gauge")
	public Integer getChassisGauge() {
		return this.chassisGauge;
	}

	public void setChassisGauge(Integer chassisGauge) {
		this.chassisGauge = chassisGauge;
	}

	@Column(name = "emissions", precision = 22, scale = 0)
	public Double getEmissions() {
		return this.emissions;
	}

	public void setEmissions(Double emissions) {
		this.emissions = emissions;
	}

	@Column(name = "engine_config", length = 3)
	public String getEngineConfig() {
		return this.engineConfig;
	}

	public void setEngineConfig(String engineConfig) {
		this.engineConfig = engineConfig;
	}

	@Column(name = "drive_mode", length = 3)
	public String getDriveMode() {
		return this.driveMode;
	}

	public void setDriveMode(String driveMode) {
		this.driveMode = driveMode;
	}

	@Column(name = "suspension_system", length = 5)
	public String getSuspensionSystem() {
		return this.suspensionSystem;
	}

	public void setSuspensionSystem(String suspensionSystem) {
		this.suspensionSystem = suspensionSystem;
	}

	@Column(name = "power_type", nullable = false, length = 5)
	public String getPowerType() {
		return this.powerType;
	}

	public void setPowerType(String powerType) {
		this.powerType = powerType;
	}

	@Column(name = "linear_type", length = 3)
	public String getLinearType() {
		return this.linearType;
	}

	public void setLinearType(String linearType) {
		this.linearType = linearType;
	}

	@Column(name = "tyre_size", length = 50)
	public String getTyreSize() {
		return this.tyreSize;
	}

	public void setTyreSize(String tyreSize) {
		this.tyreSize = tyreSize;
	}

	@Column(name = "net_weight", precision = 22, scale = 0)
	public Double getNetWeight() {
		return this.netWeight;
	}

	public void setNetWeight(Double netWeight) {
		this.netWeight = netWeight;
	}

	@Column(name = "max_total_mass", precision = 22, scale = 0)
	public Double getMaxTotalMass() {
		return this.maxTotalMass;
	}

	public void setMaxTotalMass(Double maxTotalMass) {
		this.maxTotalMass = maxTotalMass;
	}

	@Column(name = "door_num")
	public Integer getDoorNum() {
		return this.doorNum;
	}

	public void setDoorNum(Integer doorNum) {
		this.doorNum = doorNum;
	}

	@Column(name = "searting")
	public Integer getSearting() {
		return this.searting;
	}

	public void setSearting(Integer searting) {
		this.searting = searting;
	}

	@Column(name = "boot_vol", precision = 22, scale = 0)
	public Double getBootVol() {
		return this.bootVol;
	}

	public void setBootVol(Double bootVol) {
		this.bootVol = bootVol;
	}

	@Column(name = "fuel_tank", precision = 22, scale = 0)
	public Double getFuelTank() {
		return this.fuelTank;
	}

	public void setFuelTank(Double fuelTank) {
		this.fuelTank = fuelTank;
	}

	@Column(name = "auto_color")
	public Integer getAutoColor() {
		return this.autoColor;
	}

	public void setAutoColor(Integer autoColor) {
		this.autoColor = autoColor;
	}

	@Column(name = "antenna_type", length = 3)
	public String getAntennaType() {
		return this.antennaType;
	}

	public void setAntennaType(String antennaType) {
		this.antennaType = antennaType;
	}

	@Column(name = "auto_window", length = 20)
	public String getAutoWindow() {
		return this.autoWindow;
	}

	public void setAutoWindow(String autoWindow) {
		this.autoWindow = autoWindow;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createtime", length = 10)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updatetime", length = 10)
	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	@Column(name = "function_config", length = 50)
	public String getFunctionConfig() {
		return this.functionConfig;
	}

	public void setFunctionConfig(String functionConfig) {
		this.functionConfig = functionConfig;
	}

	@Column(name = "comfort_config", length = 50)
	public String getComfortConfig() {
		return this.comfortConfig;
	}

	public void setComfortConfig(String comfortConfig) {
		this.comfortConfig = comfortConfig;
	}

	@Column(name = "safe_config", length = 50)
	public String getSafeConfig() {
		return this.safeConfig;
	}

	public void setSafeConfig(String safeConfig) {
		this.safeConfig = safeConfig;
	}

	@Column(name = "remark", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
