package com.automobile.model;

// Generated 2015-4-7 21:58:34 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TLog generated by hbm2java
 */
@Entity
@Table(name = "t_log", catalog = "automobile_db")
public class Log implements java.io.Serializable {

	private Integer logId;
	private int userId;
	private Date logDate;
	private String logOp;
	private String logRemark;

	public Log() {
	}

	public Log(int userId, Date logDate, String logOp) {
		this.userId = userId;
		this.logDate = logDate;
		this.logOp = logOp;
	}

	public Log(int userId, Date logDate, String logOp, String logRemark) {
		this.userId = userId;
		this.logDate = logDate;
		this.logOp = logOp;
		this.logRemark = logRemark;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "log_id", unique = true, nullable = false)
	public Integer getLogId() {
		return this.logId;
	}

	public void setLogId(Integer logId) {
		this.logId = logId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "log_date", nullable = false, length = 10)
	public Date getLogDate() {
		return this.logDate;
	}

	public void setLogDate(Date logDate) {
		this.logDate = logDate;
	}

	@Column(name = "log_op", nullable = false, length = 50)
	public String getLogOp() {
		return this.logOp;
	}

	public void setLogOp(String logOp) {
		this.logOp = logOp;
	}

	@Column(name = "log_remark", length = 50)
	public String getLogRemark() {
		return this.logRemark;
	}

	public void setLogRemark(String logRemark) {
		this.logRemark = logRemark;
	}

}
