package com.automobile.model;

// Generated 2015-4-7 21:58:34 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TModule generated by hbm2java
 */
@Entity
@Table(name = "t_module", catalog = "automobile_db")
public class Module implements java.io.Serializable {

	private Integer moduleId;
	private String moduleName;
	private int parentId;
	private String modouleUrl;
	private String email;
	private String moduleRemark;

	public Module() {
	}

	public Module(int parentId) {
		this.parentId = parentId;
	}

	public Module(String moduleName, int parentId, String modouleUrl,
			String email, String moduleRemark) {
		this.moduleName = moduleName;
		this.parentId = parentId;
		this.modouleUrl = modouleUrl;
		this.email = email;
		this.moduleRemark = moduleRemark;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "module_id", unique = true, nullable = false)
	public Integer getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(Integer moduleId) {
		this.moduleId = moduleId;
	}

	@Column(name = "module_name", length = 20)
	public String getModuleName() {
		return this.moduleName;
	}

	public void setModuleName(String moduleName) {
		this.moduleName = moduleName;
	}

	@Column(name = "parent_id", nullable = false)
	public int getParentId() {
		return this.parentId;
	}

	public void setParentId(int parentId) {
		this.parentId = parentId;
	}

	@Column(name = "modoule_url", length = 50)
	public String getModouleUrl() {
		return this.modouleUrl;
	}

	public void setModouleUrl(String modouleUrl) {
		this.modouleUrl = modouleUrl;
	}

	@Column(name = "email", length = 20)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "module_remark", length = 50)
	public String getModuleRemark() {
		return this.moduleRemark;
	}

	public void setModuleRemark(String moduleRemark) {
		this.moduleRemark = moduleRemark;
	}

}
