package com.automobile.model;

// Generated 2015-4-7 21:58:34 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TOutinstorageH generated by hbm2java
 */
@Entity
@Table(name = "t_outinstorage_h", catalog = "automobile_db")
public class OutinstorageH implements java.io.Serializable {

	private Integer pkOutinH;
	private String outinflag;
	private String billCode;
	private Integer stoId;
	private Integer userId;
	private Date outinDate;
	private String remark;
	private Set<OutinstorageB> OutinstorageBs = new HashSet<OutinstorageB>(0);

	public OutinstorageH() {
	}

	public OutinstorageH(String outinflag, String billCode) {
		this.outinflag = outinflag;
		this.billCode = billCode;
	}

	public OutinstorageH(String outinflag, String billCode, Integer stoId,
			Integer userId, Date outinDate, String remark,
			Set<OutinstorageB> OutinstorageBs) {
		this.outinflag = outinflag;
		this.billCode = billCode;
		this.stoId = stoId;
		this.userId = userId;
		this.outinDate = outinDate;
		this.remark = remark;
		this.OutinstorageBs = OutinstorageBs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "pk_outin_h", unique = true, nullable = false)
	public Integer getPkOutinH() {
		return this.pkOutinH;
	}

	public void setPkOutinH(Integer pkOutinH) {
		this.pkOutinH = pkOutinH;
	}

	@Column(name = "outinflag", nullable = false, length = 10)
	public String getOutinflag() {
		return this.outinflag;
	}

	public void setOutinflag(String outinflag) {
		this.outinflag = outinflag;
	}

	@Column(name = "bill_code", nullable = false, length = 10)
	public String getBillCode() {
		return this.billCode;
	}

	public void setBillCode(String billCode) {
		this.billCode = billCode;
	}

	@Column(name = "sto_id")
	public Integer getStoId() {
		return this.stoId;
	}

	public void setStoId(Integer stoId) {
		this.stoId = stoId;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "outin_date", length = 10)
	public Date getOutinDate() {
		return this.outinDate;
	}

	public void setOutinDate(Date outinDate) {
		this.outinDate = outinDate;
	}

	@Column(name = "remark", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "TOutinstorageH")
	public Set<OutinstorageB> getTOutinstorageBs() {
		return this.OutinstorageBs;
	}

	public void setTOutinstorageBs(Set<OutinstorageB> OutinstorageBs) {
		this.OutinstorageBs = OutinstorageBs;
	}

}
