package com.automobile.model;

// Generated 2015-4-7 21:58:34 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TPower generated by hbm2java
 */
@Entity
@Table(name = "t_power", catalog = "automobile_db")
public class Power implements java.io.Serializable {

	private Integer powerId;
	private int roleId;
	private int moduleId;
	private Boolean add;
	private Boolean del;
	private Boolean update;
	private Boolean select;
	private String powerRemark;

	public Power() {
	}

	public Power(int roleId, int moduleId) {
		this.roleId = roleId;
		this.moduleId = moduleId;
	}

	public Power(int roleId, int moduleId, Boolean add, Boolean del,
			Boolean update, Boolean select, String powerRemark) {
		this.roleId = roleId;
		this.moduleId = moduleId;
		this.add = add;
		this.del = del;
		this.update = update;
		this.select = select;
		this.powerRemark = powerRemark;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "power_id", unique = true, nullable = false)
	public Integer getPowerId() {
		return this.powerId;
	}

	public void setPowerId(Integer powerId) {
		this.powerId = powerId;
	}

	@Column(name = "role_id", nullable = false)
	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	@Column(name = "module_id", nullable = false)
	public int getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(int moduleId) {
		this.moduleId = moduleId;
	}

	@Column(name = "add")
	public Boolean getAdd() {
		return this.add;
	}

	public void setAdd(Boolean add) {
		this.add = add;
	}

	@Column(name = "del")
	public Boolean getDel() {
		return this.del;
	}

	public void setDel(Boolean del) {
		this.del = del;
	}

	@Column(name = "update")
	public Boolean getUpdate() {
		return this.update;
	}

	public void setUpdate(Boolean update) {
		this.update = update;
	}

	@Column(name = "select")
	public Boolean getSelect() {
		return this.select;
	}

	public void setSelect(Boolean select) {
		this.select = select;
	}

	@Column(name = "power_remark", length = 50)
	public String getPowerRemark() {
		return this.powerRemark;
	}

	public void setPowerRemark(String powerRemark) {
		this.powerRemark = powerRemark;
	}

}
