package com.automobile.model;

// Generated 2015-4-7 21:58:34 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SalevoucherH generated by hbm2java
 */
@Entity
@Table(name = "t_salevoucher_h", catalog = "automobile_db")
public class SalevoucherH implements java.io.Serializable {

	private Integer pkSvH;
	private String saleId;
	private int customerType;
	private int customerId;
	private Date saleDate;
	private int stoId;
	private int userId;
	private Boolean isPay;
	private Integer taxId;
	private Double beforeTax;
	private Double taxMoney;
	private Double afterTax;
	private Double totalMoney;
	private String remark;

	public SalevoucherH() {
	}

	public SalevoucherH(String saleId, int customerType, int customerId,
			Date saleDate, int stoId, int userId) {
		this.saleId = saleId;
		this.customerType = customerType;
		this.customerId = customerId;
		this.saleDate = saleDate;
		this.stoId = stoId;
		this.userId = userId;
	}

	public SalevoucherH(String saleId, int customerType, int customerId,
			Date saleDate, int stoId, int userId, Boolean isPay, Integer taxId,
			Double beforeTax, Double taxMoney, Double afterTax,
			Double totalMoney, String remark) {
		this.saleId = saleId;
		this.customerType = customerType;
		this.customerId = customerId;
		this.saleDate = saleDate;
		this.stoId = stoId;
		this.userId = userId;
		this.isPay = isPay;
		this.taxId = taxId;
		this.beforeTax = beforeTax;
		this.taxMoney = taxMoney;
		this.afterTax = afterTax;
		this.totalMoney = totalMoney;
		this.remark = remark;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "pk_sv_h", unique = true, nullable = false)
	public Integer getPkSvH() {
		return this.pkSvH;
	}

	public void setPkSvH(Integer pkSvH) {
		this.pkSvH = pkSvH;
	}

	@Column(name = "sale_id", nullable = false, length = 20)
	public String getSaleId() {
		return this.saleId;
	}

	public void setSaleId(String saleId) {
		this.saleId = saleId;
	}

	@Column(name = "customer_type", nullable = false)
	public int getCustomerType() {
		return this.customerType;
	}

	public void setCustomerType(int customerType) {
		this.customerType = customerType;
	}

	@Column(name = "customer_id", nullable = false)
	public int getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "sale_date", nullable = false, length = 10)
	public Date getSaleDate() {
		return this.saleDate;
	}

	public void setSaleDate(Date saleDate) {
		this.saleDate = saleDate;
	}

	@Column(name = "sto_id", nullable = false)
	public int getStoId() {
		return this.stoId;
	}

	public void setStoId(int stoId) {
		this.stoId = stoId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "is_pay")
	public Boolean getIsPay() {
		return this.isPay;
	}

	public void setIsPay(Boolean isPay) {
		this.isPay = isPay;
	}

	@Column(name = "tax_id")
	public Integer getTaxId() {
		return this.taxId;
	}

	public void setTaxId(Integer taxId) {
		this.taxId = taxId;
	}

	@Column(name = "before_tax", precision = 22, scale = 0)
	public Double getBeforeTax() {
		return this.beforeTax;
	}

	public void setBeforeTax(Double beforeTax) {
		this.beforeTax = beforeTax;
	}

	@Column(name = "tax_money", precision = 22, scale = 0)
	public Double getTaxMoney() {
		return this.taxMoney;
	}

	public void setTaxMoney(Double taxMoney) {
		this.taxMoney = taxMoney;
	}

	@Column(name = "after_tax", precision = 22, scale = 0)
	public Double getAfterTax() {
		return this.afterTax;
	}

	public void setAfterTax(Double afterTax) {
		this.afterTax = afterTax;
	}

	@Column(name = "total_money", precision = 22, scale = 0)
	public Double getTotalMoney() {
		return this.totalMoney;
	}

	public void setTotalMoney(Double totalMoney) {
		this.totalMoney = totalMoney;
	}

	@Column(name = "remark", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
