package com.automobile.model;

// Generated 2015-4-7 21:58:34 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SaleplanId generated by hbm2java
 */
@Embeddable
public class SaleplanId implements java.io.Serializable {

	private int id;
	private String planId;

	public SaleplanId() {
	}

	public SaleplanId(int id, String planId) {
		this.id = id;
		this.planId = planId;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "plan_id", nullable = false, length = 20)
	public String getPlanId() {
		return this.planId;
	}

	public void setPlanId(String planId) {
		this.planId = planId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SaleplanId))
			return false;
		SaleplanId castOther = (SaleplanId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getPlanId() == castOther.getPlanId()) || (this
						.getPlanId() != null && castOther.getPlanId() != null && this
						.getPlanId().equals(castOther.getPlanId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result
				+ (getPlanId() == null ? 0 : this.getPlanId().hashCode());
		return result;
	}

}
