package com.automobile.model;

// Generated 2015-4-7 21:58:34 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SalevoucherB generated by hbm2java
 */
@Entity
@Table(name = "t_salevoucher_b", catalog = "automobile_db")
public class SalevoucherB implements java.io.Serializable {

	private Integer pkSvB;
	private int pkSvH;
	private String autoTypeId;
	private String autoId;
	private Double salePrice;
	private Double saleNum;
	private Double beforeTax;
	private Double taxMoney;
	private Double afterTax;
	private Double tempMoney;

	public SalevoucherB() {
	}

	public SalevoucherB(int pkSvH, String autoTypeId, String autoId) {
		this.pkSvH = pkSvH;
		this.autoTypeId = autoTypeId;
		this.autoId = autoId;
	}

	public SalevoucherB(int pkSvH, String autoTypeId, String autoId,
			Double salePrice, Double saleNum, Double beforeTax,
			Double taxMoney, Double afterTax, Double tempMoney) {
		this.pkSvH = pkSvH;
		this.autoTypeId = autoTypeId;
		this.autoId = autoId;
		this.salePrice = salePrice;
		this.saleNum = saleNum;
		this.beforeTax = beforeTax;
		this.taxMoney = taxMoney;
		this.afterTax = afterTax;
		this.tempMoney = tempMoney;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "pk_sv_b", unique = true, nullable = false)
	public Integer getPkSvB() {
		return this.pkSvB;
	}

	public void setPkSvB(Integer pkSvB) {
		this.pkSvB = pkSvB;
	}

	@Column(name = "pk_sv_h", nullable = false)
	public int getPkSvH() {
		return this.pkSvH;
	}

	public void setPkSvH(int pkSvH) {
		this.pkSvH = pkSvH;
	}

	@Column(name = "auto_type_id", nullable = false, length = 20)
	public String getAutoTypeId() {
		return this.autoTypeId;
	}

	public void setAutoTypeId(String autoTypeId) {
		this.autoTypeId = autoTypeId;
	}

	@Column(name = "auto_id", nullable = false, length = 20)
	public String getAutoId() {
		return this.autoId;
	}

	public void setAutoId(String autoId) {
		this.autoId = autoId;
	}

	@Column(name = "sale_price", precision = 22, scale = 0)
	public Double getSalePrice() {
		return this.salePrice;
	}

	public void setSalePrice(Double salePrice) {
		this.salePrice = salePrice;
	}

	@Column(name = "sale_num", precision = 22, scale = 0)
	public Double getSaleNum() {
		return this.saleNum;
	}

	public void setSaleNum(Double saleNum) {
		this.saleNum = saleNum;
	}

	@Column(name = "before_tax", precision = 22, scale = 0)
	public Double getBeforeTax() {
		return this.beforeTax;
	}

	public void setBeforeTax(Double beforeTax) {
		this.beforeTax = beforeTax;
	}

	@Column(name = "tax_money", precision = 22, scale = 0)
	public Double getTaxMoney() {
		return this.taxMoney;
	}

	public void setTaxMoney(Double taxMoney) {
		this.taxMoney = taxMoney;
	}

	@Column(name = "after_tax", precision = 22, scale = 0)
	public Double getAfterTax() {
		return this.afterTax;
	}

	public void setAfterTax(Double afterTax) {
		this.afterTax = afterTax;
	}

	@Column(name = "temp_money", precision = 22, scale = 0)
	public Double getTempMoney() {
		return this.tempMoney;
	}

	public void setTempMoney(Double tempMoney) {
		this.tempMoney = tempMoney;
	}

}
