package com.automobile.model;

// Generated 2015-4-7 21:58:34 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * StoInventory generated by hbm2java
 */
@Entity
@Table(name = "t_StoInventory", catalog = "automobile_db")
public class StoInventory implements java.io.Serializable {

	private Integer id;
	private Integer stoId;
	private String autoTypeId;
	private Integer invNum;
	private Integer warningNum;
	private String remark;

	public StoInventory() {
	}

	public StoInventory(String autoTypeId) {
		this.autoTypeId = autoTypeId;
	}

	public StoInventory(Integer stoId, String autoTypeId, Integer invNum,
			Integer warningNum, String remark) {
		this.stoId = stoId;
		this.autoTypeId = autoTypeId;
		this.invNum = invNum;
		this.warningNum = warningNum;
		this.remark = remark;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "sto_id")
	public Integer getStoId() {
		return this.stoId;
	}

	public void setStoId(Integer stoId) {
		this.stoId = stoId;
	}

	@Column(name = "auto_type_id", nullable = false, length = 20)
	public String getAutoTypeId() {
		return this.autoTypeId;
	}

	public void setAutoTypeId(String autoTypeId) {
		this.autoTypeId = autoTypeId;
	}

	@Column(name = "inv_num")
	public Integer getInvNum() {
		return this.invNum;
	}

	public void setInvNum(Integer invNum) {
		this.invNum = invNum;
	}

	@Column(name = "warning_num")
	public Integer getWarningNum() {
		return this.warningNum;
	}

	public void setWarningNum(Integer warningNum) {
		this.warningNum = warningNum;
	}

	@Column(name = "remark", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
