package com.automobile.model;

// Generated 2015-4-7 21:58:34 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UtilityBillId generated by hbm2java
 */
@Embeddable
public class UtilityBillId implements java.io.Serializable {

	private int id;
	private String ubId;

	public UtilityBillId() {
	}

	public UtilityBillId(int id, String ubId) {
		this.id = id;
		this.ubId = ubId;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "ub_id", nullable = false, length = 10)
	public String getUbId() {
		return this.ubId;
	}

	public void setUbId(String ubId) {
		this.ubId = ubId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UtilityBillId))
			return false;
		UtilityBillId castOther = (UtilityBillId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getUbId() == castOther.getUbId()) || (this.getUbId() != null
						&& castOther.getUbId() != null && this.getUbId()
						.equals(castOther.getUbId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result
				+ (getUbId() == null ? 0 : this.getUbId().hashCode());
		return result;
	}

}
