package com.automobile.model;

// Generated 2015-4-7 21:58:34 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Utilitybill generated by hbm2java
 */
@Entity
@Table(name = "t_utilitybill", catalog = "automobile_db")
public class Utilitybill implements java.io.Serializable {

	private UtilitybillId id;
	private Date ubDate;
	private Integer ubType;
	private Integer sid;
	private Double ubMon;
	private String ubUser;
	private Date ubMkDate;
	private String remark;

	public Utilitybill() {
	}

	public Utilitybill(UtilitybillId id) {
		this.id = id;
	}

	public Utilitybill(UtilitybillId id, Date ubDate, Integer ubType,
			Integer sid, Double ubMon, String ubUser, Date ubMkDate,
			String remark) {
		this.id = id;
		this.ubDate = ubDate;
		this.ubType = ubType;
		this.sid = sid;
		this.ubMon = ubMon;
		this.ubUser = ubUser;
		this.ubMkDate = ubMkDate;
		this.remark = remark;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "ubId", column = @Column(name = "ub_id", nullable = false, length = 10)) })
	public UtilitybillId getId() {
		return this.id;
	}

	public void setId(UtilitybillId id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ub_date", length = 10)
	public Date getUbDate() {
		return this.ubDate;
	}

	public void setUbDate(Date ubDate) {
		this.ubDate = ubDate;
	}

	@Column(name = "ub_type")
	public Integer getUbType() {
		return this.ubType;
	}

	public void setUbType(Integer ubType) {
		this.ubType = ubType;
	}

	@Column(name = "sid")
	public Integer getSid() {
		return this.sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}

	@Column(name = "ub_mon", precision = 22, scale = 0)
	public Double getUbMon() {
		return this.ubMon;
	}

	public void setUbMon(Double ubMon) {
		this.ubMon = ubMon;
	}

	@Column(name = "ub_user", length = 200)
	public String getUbUser() {
		return this.ubUser;
	}

	public void setUbUser(String ubUser) {
		this.ubUser = ubUser;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ub_mk_date", length = 10)
	public Date getUbMkDate() {
		return this.ubMkDate;
	}

	public void setUbMkDate(Date ubMkDate) {
		this.ubMkDate = ubMkDate;
	}

	@Column(name = "remark", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
